### ISSUE TITLE
KissManga not working

### ISSUE THREAD

**Issue by 40days** [klaxa/batotocrawler#11]
First of all, I've been using this program for a long time, thank you for your work!

Recently, the KissManga crawler stopped working, which is horrible since it also, recently, became impossible to download full mangas from bato.to due to its policy change.

Well, maybe the problem is on my end, but I'll leave the traceback here.

 Traceback (most recent call last):
  File "/home/40days/Documents/programs/batotocrawler-master/Manager.py", line 209, in <module>
    manga = KissManga(url)
  File "/home/40days/Documents/programs/batotocrawler-master/Scrapers/KissManga.py", line 23, in **init**
    self.page = BeautifulSoup(self.open_url(url))
  File "/home/40days/Documents/programs/batotocrawler-master/Scrapers/KissManga.py", line 119, in open_url
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

**Comment by klaxa** [comment]
Hi,

a 5xx Error is usually a server error and not a bug in the software.
Take a look at the error code:

> urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

Did you try to access the site with a browser to check it's not an issue on kissmanga's website?

**Comment by 40days** [comment]
So, I'm assuming it works on your end? If it does, don't bother!

> Did you try to access the site with a browser to check it's not an issue on kissmanga's website?

Yes, I can access, for example http://kissmanga.com/Manga/Shokugeki-no-Soma/Chapter-142?id=251262  , but the script doesn't work:

> _$ python ~/Documents/programs/batotocrawler-master/Manager.py --cbz -d '%title' http://kissmanga.com/Manga/Shokugeki-no-Soma/Chapter-142?id=251262_
> Traceback (most recent call last):
> File "/home/40days/Documents/programs/batotocrawler-master/Manager.py", line 209, in ><module>
> etc.....
> urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

After reading http://stackoverflow.com/questions/27354960/python-urllib2-urlopen-returns-a-http-error-503/27355049#27355049 , I tried to do _curl -i http://kissmanga.com/Manga/Shokugeki-no-Soma/Chapter-142?id=251262_ and the output is also 'HTTP/1.1 503 Service Temporarily Unavailable' along with the rest of the HTML with a bunch of "Please turn JavaScript on (...)" warnings

**Comment by klaxa** [comment]
I just realized, this is the batotocrawler project, I've kinda stopped working on it since someone else did a better job: https://github.com/Hamuko/cum maybe try that instead? The user interface is a lot better and easier for following current releases.

**Comment by 40days** [comment]
Oh, okay, that works too!
Thank you for your attention!
