### ISSUE TITLE
Batoto no longer works

### ISSUE THREAD

**Issue by Sohil876** [klaxa/batotocrawler#12]
Batoto module no longer works, looks like its unable to get chapter information.

**Comment by klaxa** [comment]
Head over to [https://github.com/Hamuko/cum](https://github.com/Hamuko/cum). This project is pretty much deprecated since cum does a much better job at everything.

**Comment by Sohil876** [comment]
Thanks for that, however that wont work for me as i wanted it for a mobile device with old libraries (N900), sql alchemy for python3 is the problem. I need a simple manga downloader like yours.
